apiVersion: skaffold/v2beta12
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: cheatcodesam/foodfinder-server
      context: backend
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "foodfinder/**/*.py"
            dest: .
          - src: "users/**/*.py"
            dest: .
          - src: "geofinder/**/*.py"
            dest: .
deploy:
  kubectl:
    manifests:
      - ./k8s/*
