apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: cheatcodesam/foodfinder-server
          ports:
            - containerPort: 8000
          env:
            - name: CELERY_BROKER
              value: redis://redis-cluster-ip-service:6379
            - name: SQL_ENGINE
              value: django.db.backends.postgresql
            - name: SQL_DATABASE
              value: postgres
            - name: SQL_USER
              value: postgres
            - name: SQL_PASSWORD
              value: postgres
            - name: SQL_HOST
              value: postgres-cluster-ip-service
            - name: SQL_PORT
              value: "5432"
