# Generated by Django 4.0.1 on 2022-05-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geofinder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.CharField(default='g', max_length=100),
            preserve_default=False,
        ),
    ]
