# Generated by Django 4.0.1 on 2022-05-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geofinder', '0003_business_city_business_state_business_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
