# Generated by Django 4.0.1 on 2022-05-06 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geofinder', '0004_alter_business_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='method_for_query',
            field=models.CharField(choices=[('LD', 'Loading'), ('NA', 'None'), ('MU', 'Menu'), ('RC', 'Recommended'), ('RD', 'Ready')], default='RD', max_length=2),
        ),
    ]
