# Generated by Django 4.0.1 on 2022-05-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geofinder', '0006_alter_business_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='business',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='business',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='state',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='business',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
